import { WebMCPOptionItem } from './types';

// ============================================================================
// DETERMINISTIC DATASET: 50+ ITEMS FOR LOCAL WEBMCP EXECUTION
// ============================================================================

export const MOCK_WEBMCP_DATABASE: WebMCPOptionItem[] = [
  // --- ACCOMMODATIONS (10 items) ---
  {
    id: 'acc_01',
    name: 'EcoLodge Canopy Suites',
    category: 'accommodations',
    price: 135,
    rating: 4.9,
    sustainabilityScore: 98,
    description: '100% solar-powered geodome in redwood valley with zero-waste toiletries and rainwater harvesting.',
    location: 'Valley Ridge, Zone 4',
    tags: ['solar-powered', 'zero-waste', 'geodome', 'eco-certified', 'quiet'],
  },
  {
    id: 'acc_02',
    name: 'Solar Lofts & Botanicals',
    category: 'accommodations',
    price: 98,
    rating: 4.8,
    sustainabilityScore: 95,
    description: 'LEED Platinum certified urban loft adjacent to light rail transit with compost hub and rooftop herb garden.',
    location: 'Transit District, Downtown East',
    tags: ['transit-adjacent', 'leed-platinum', 'urban', 'solar', 'budget-friendly'],
  },
  {
    id: 'acc_03',
    name: 'Green Harbor Tiny Cabins',
    category: 'accommodations',
    price: 110,
    rating: 4.7,
    sustainabilityScore: 92,
    description: 'Reclaimed timber micro-cabins overlooking freshwater estuary with shared electric cargo bikes.',
    location: 'Harbor Point, South Pier',
    tags: ['reclaimed-wood', 'bikes-included', 'waterfront', 'micro-living'],
  },
  {
    id: 'acc_04',
    name: 'BioDune Earthship Retreat',
    category: 'accommodations',
    price: 160,
    rating: 4.9,
    sustainabilityScore: 99,
    description: 'Passive thermal earth-sheltered home maintaining 70°F year-round with indoor food forest.',
    location: 'Highland Dunes, Eco Corridor',
    tags: ['passive-thermal', 'earthship', 'permaculture', 'luxury-eco'],
  },
  {
    id: 'acc_05',
    name: 'Metropolis Circular Hotel',
    category: 'accommodations',
    price: 145,
    rating: 4.6,
    sustainabilityScore: 88,
    description: 'Modern boutique hotel with 100% renewable grid power, organic linen, and carbon-offset stays.',
    location: 'Arts District Central',
    tags: ['circular-economy', 'renewable-grid', 'arts-district', 'modern'],
  },
  {
    id: 'acc_06',
    name: 'Meadowlands Yurt Sanctuary',
    category: 'accommodations',
    price: 85,
    rating: 4.8,
    sustainabilityScore: 94,
    description: 'Handcrafted wool yurt with high-efficiency pellet stove, solar LED lighting, and organic breakfast baskets.',
    location: 'Meadow Preserve North',
    tags: ['yurt', 'organic-breakfast', 'stargazing', 'low-impact'],
  },
  {
    id: 'acc_07',
    name: 'Creekside Timber Lodge',
    category: 'accommodations',
    price: 125,
    rating: 4.5,
    sustainabilityScore: 89,
    description: 'FSC-certified timber cabin along salmon restoration stream with thermal heat pump.',
    location: 'Bear Creek Trailhead',
    tags: ['fsc-timber', 'heat-pump', 'nature', 'creekside'],
  },
  {
    id: 'acc_08',
    name: 'Urban Sprout Pod Hotel',
    category: 'accommodations',
    price: 65,
    rating: 4.4,
    sustainabilityScore: 86,
    description: 'Minimalist smart micro-pods with shared aeroponic lounge and high-efficiency thermal envelopes.',
    location: 'Civic Center Hub',
    tags: ['micro-pod', 'ultra-budget', 'aeroponic', 'minimalist'],
  },
  {
    id: 'acc_09',
    name: 'Orchard Hill Agro-Stay',
    category: 'accommodations',
    price: 115,
    rating: 4.9,
    sustainabilityScore: 96,
    description: 'Restored farmhouse within working regenerative apple orchard with biochar heating.',
    location: 'Orchard Valley West',
    tags: ['regenerative-farm', 'farmstay', 'apple-orchard', 'biochar'],
  },
  {
    id: 'acc_10',
    name: 'Coastal Kelp Bed B&B',
    category: 'accommodations',
    price: 150,
    rating: 4.7,
    sustainabilityScore: 91,
    description: 'Ocean-facing cottage powered by tidal and wind energy, supporting local kelp reef restoration.',
    location: 'Point Marina Coast',
    tags: ['marine-restoration', 'tidal-power', 'coastal', 'ocean-view'],
  },

  // --- TRANSPORT (10 items) ---
  {
    id: 'trn_01',
    name: 'All-Electric High-Speed Light Rail 3-Day Pass',
    category: 'transport',
    price: 24,
    rating: 4.9,
    sustainabilityScore: 99,
    description: 'Unlimited 72-hour pass for zero-emission rail grid connecting city center, coastal trails, and valleys.',
    location: 'Metro Rail System Wide',
    tags: ['zero-emission', 'light-rail', 'unlimited-pass', 'best-value'],
  },
  {
    id: 'trn_02',
    name: 'Community E-Bike Tandem / Pair Rental',
    category: 'transport',
    price: 36,
    rating: 4.8,
    sustainabilityScore: 98,
    description: 'Pair of smart solar-charged e-bikes with panniers, locks, and dedicated protected greenway access.',
    location: 'Greenway Hubs (24 Stations)',
    tags: ['e-bike', 'solar-charged', 'pair-rental', 'greenway'],
  },
  {
    id: 'trn_03',
    name: 'Renewable Electric Ferry Cruiser',
    category: 'transport',
    price: 18,
    rating: 4.8,
    sustainabilityScore: 96,
    description: 'Battery-electric scenic passenger catamaran connecting harbor districts and nature island preserves.',
    location: 'Harbor Gate 4',
    tags: ['electric-ferry', 'scenic', 'island-access', 'clean-marine'],
  },
  {
    id: 'trn_04',
    name: 'Shared Clean-Grid EV Microcar (Day Rate)',
    category: 'transport',
    price: 48,
    rating: 4.5,
    sustainabilityScore: 87,
    description: 'Compact 2-seater neighborhood electric vehicle with free municipal charging and reserved green parking.',
    location: 'Downtown Mobility Hubs',
    tags: ['ev-carshare', 'microcar', 'free-charging'],
  },
  {
    id: 'trn_05',
    name: 'Greenway Solar Tram Tour Pass',
    category: 'transport',
    price: 16,
    rating: 4.7,
    sustainabilityScore: 95,
    description: 'Hop-on hop-off open-air electric tram circling the botanical gardens and historical arts loop.',
    location: 'Central Loop Stations',
    tags: ['hop-on-hop-off', 'tram', 'botanical-route', 'scenic'],
  },
  {
    id: 'trn_06',
    name: 'Pedal-Assist Cargo Trike with Canopy',
    category: 'transport',
    price: 30,
    rating: 4.6,
    sustainabilityScore: 99,
    description: 'Spacious 3-wheel electric cargo bicycle for hauling picnic baskets, farm-stand produce, and gear.',
    location: 'Farmers Market Depot',
    tags: ['cargo-trike', 'picnic-ready', 'zero-emission', 'fun'],
  },
  {
    id: 'trn_07',
    name: 'Express Biofuel Rapid Shuttle',
    category: 'transport',
    price: 14,
    rating: 4.4,
    sustainabilityScore: 84,
    description: 'Waste-oil biodiesel commuter coach directly connecting the regional airport to the eco-lodges.',
    location: 'Regional Intermodal Terminal',
    tags: ['biodiesel', 'airport-link', 'budget'],
  },
  {
    id: 'trn_08',
    name: 'Forest Railway Heritage Scenic Train',
    category: 'transport',
    price: 32,
    rating: 4.8,
    sustainabilityScore: 88,
    description: 'Historic railway converted to hydrogen fuel-cell power, gliding through old-growth cedar canyons.',
    location: 'Old Timber Depot',
    tags: ['hydrogen-train', 'heritage', 'cedar-canyon', 'views'],
  },
  {
    id: 'trn_09',
    name: 'Walking Audio Trail & Guided Transit Badge',
    category: 'transport',
    price: 8,
    rating: 4.9,
    sustainabilityScore: 100,
    description: 'Curated 15km pedestrian wayfinding pass with GPS audio storytelling and hydration refill access.',
    location: 'Citywide Trail System',
    tags: ['zero-carbon', 'walking', 'audio-guide', 'hydration-stations'],
  },
  {
    id: 'trn_10',
    name: 'Coastal Kayak Point-to-Point Shuttle',
    category: 'transport',
    price: 28,
    rating: 4.7,
    sustainabilityScore: 97,
    description: 'Paddle one-way along the estuary and have your kayak picked up at the estuary eco-center.',
    location: 'North River Launch',
    tags: ['kayak-shuttle', 'water-trail', 'adventure', 'clean'],
  },

  // --- RESTAURANTS & DINING (10 items) ---
  {
    id: 'rst_01',
    name: 'Soil & Sprout Zero-Waste Bistro',
    category: 'restaurants',
    price: 32,
    rating: 4.9,
    sustainabilityScore: 98,
    description: 'Hyper-local 5-course tasting menu sourced within 15 miles with closed-loop kitchen composting.',
    location: 'Garden Quarter, Block 7',
    tags: ['zero-waste', 'hyper-local', 'farm-to-table', 'organic-wine', 'michelin-green'],
  },
  {
    id: 'rst_02',
    name: 'Wild Forage Hearth & Bakery',
    category: 'restaurants',
    price: 22,
    rating: 4.8,
    sustainabilityScore: 96,
    description: 'Artisan sourdough, ancient grain woodfired flatbreads, and wild mushroom broths sourced ethically.',
    location: 'Old Mill Court',
    tags: ['ancient-grains', 'wild-forage', 'woodfired', 'sourdough', 'cozy'],
  },
  {
    id: 'rst_03',
    name: 'Oceanic Restorative Oyster & Kelp Bar',
    category: 'restaurants',
    price: 28,
    rating: 4.9,
    sustainabilityScore: 97,
    description: 'Regenerative bivalves and seaweed salads that purify bay water while providing clean coastal cuisine.',
    location: 'Pier 9 Waterfront',
    tags: ['regenerative-seafood', 'bivalves', 'kelp', 'bay-view'],
  },
  {
    id: 'rst_04',
    name: 'Roots & Shoots Plant Kitchen',
    category: 'restaurants',
    price: 18,
    rating: 4.7,
    sustainabilityScore: 95,
    description: '100% plant-based comfort bowls, cold-pressed elixirs, and upcycled botanical desserts.',
    location: 'Uptown Market Hall',
    tags: ['plant-based', 'vegan', 'upcycled-ingredients', 'quick-casual'],
  },
  {
    id: 'rst_05',
    name: 'Co-op Harvest Table & Ciderhouse',
    category: 'restaurants',
    price: 26,
    rating: 4.8,
    sustainabilityScore: 94,
    description: 'Worker-owned cooperative serving heritage heirloom squash stews and wild fermented orchard ciders.',
    location: 'Westside Agrarian Row',
    tags: ['worker-owned', 'craft-cider', 'heirloom', 'community'],
  },
  {
    id: 'rst_06',
    name: 'Sunbeam Solar Cafe & Roastery',
    category: 'restaurants',
    price: 14,
    rating: 4.9,
    sustainabilityScore: 99,
    description: 'Direct-trade coffee roasted on-site using parabolic solar concentrators, accompanied by oat-milk pastries.',
    location: 'Sunny Slope Plaza',
    tags: ['solar-roasted', 'direct-trade', 'breakfast', 'pastries'],
  },
  {
    id: 'rst_07',
    name: 'Seedling Noodle Workshop',
    category: 'restaurants',
    price: 16,
    rating: 4.7,
    sustainabilityScore: 92,
    description: 'Hand-pulled buckwheat noodles in 24-hour roasted vegetable broth with seasonal microgreens.',
    location: 'East Asian Cultural Alley',
    tags: ['hand-pulled-noodles', 'comfort-food', 'buckwheat', 'budget'],
  },
  {
    id: 'rst_08',
    name: 'Permaculture Picnic Basket Delivery',
    category: 'restaurants',
    price: 25,
    rating: 4.8,
    sustainabilityScore: 97,
    description: 'Artisanal insulated backpack filled with local cheeses, fresh figs, herb focaccia, and cloth napkins.',
    location: 'Delivered to any park GPS',
    tags: ['picnic-delivery', 'zero-waste', 'cheeses', 'outdoor-dining'],
  },
  {
    id: 'rst_09',
    name: 'Terra Madre Woodfire Pizzeria',
    category: 'restaurants',
    price: 20,
    rating: 4.6,
    sustainabilityScore: 90,
    description: 'Organic heritage wheat sourdough pizzas topped with garden pesto and house-made plant cheeses.',
    location: 'South Commons Yard',
    tags: ['pizza', 'organic', 'sourdough', 'casual'],
  },
  {
    id: 'rst_10',
    name: 'Green Teahouse & Dim Sum Studio',
    category: 'restaurants',
    price: 24,
    rating: 4.9,
    sustainabilityScore: 96,
    description: 'Biodynamic mountain teas paired with bamboo-steamed mushroom dumplings and lotus root crisps.',
    location: 'Tranquil Gardens Courtyard',
    tags: ['dim-sum', 'biodynamic-tea', 'mindful-dining', 'zen'],
  },

  // --- EXPERIENCES & ACTIVITIES (20 items) ---
  {
    id: 'exp_01',
    name: 'Canopy Forest Bathing & Botanical Walk',
    category: 'experiences',
    price: 20,
    rating: 4.9,
    sustainabilityScore: 99,
    description: 'Certified forest therapy guide leading sensory mindfulness walking tour through 300-year-old coastal redwoods.',
    location: 'Ancient Grove Trail',
    tags: ['mindfulness', 'nature', 'forest-therapy', 'low-impact', 'wellness'],
  },
  {
    id: 'exp_02',
    name: 'Regenerative Farm Hands-On Workshop & Honey Tasting',
    category: 'experiences',
    price: 25,
    rating: 4.8,
    sustainabilityScore: 98,
    description: 'Tour rotational grazing paddocks, harvest heirloom vegetables, and taste raw single-flower wildflower honey.',
    location: 'Sun Valley Organic Farm',
    tags: ['farm-tour', 'honey-tasting', 'hands-on', 'education'],
  },
  {
    id: 'exp_03',
    name: 'Sunset Bioluminescent Estuary Kayak Paddle',
    category: 'experiences',
    price: 45,
    rating: 4.9,
    sustainabilityScore: 97,
    description: 'Guided quiet night paddle in protected marine reserve surrounded by glowing dinoflagellate phytoplankton.',
    location: 'Moonlight Cove Estuary',
    tags: ['bioluminescence', 'night-kayak', 'stargazing', 'magical', 'must-do'],
  },
  {
    id: 'exp_04',
    name: 'Solar Stargazing & Dark Sky Observatory Session',
    category: 'experiences',
    price: 15,
    rating: 4.9,
    sustainabilityScore: 100,
    description: 'High-elevation telescope viewing of Saturn rings, nebulas, and constellations in designated Dark Sky Park.',
    location: 'Summit Observatory Ridge',
    tags: ['dark-sky', 'astronomy', 'stargazing', 'educational'],
  },
  {
    id: 'exp_05',
    name: 'Wild Mushroom Foraging & Identification Masterclass',
    category: 'experiences',
    price: 35,
    rating: 4.7,
    sustainabilityScore: 96,
    description: 'Mycologist-led forest trek identifying chanterelles, lion’s mane, and oyster mushrooms with spore printing.',
    location: 'Mossy Ridge Reserve',
    tags: ['foraging', 'mycology', 'culinary', 'nature'],
  },
  {
    id: 'exp_06',
    name: 'Ceramic Stoneware & Natural Clay Workshop',
    category: 'experiences',
    price: 30,
    rating: 4.8,
    sustainabilityScore: 94,
    description: 'Throw pottery using local river clay with mineral ash glazes fired in wood-fueled kiln.',
    location: 'Riverbank Artisan Collective',
    tags: ['pottery', 'craft', 'souvenir', 'creative'],
  },
  {
    id: 'exp_07',
    name: 'Coastal Kelp Forest Snorkeling & Tidepool Ecology',
    category: 'experiences',
    price: 40,
    rating: 4.8,
    sustainabilityScore: 97,
    description: 'Eco-diver guided snorkel through clear temperate kelp beds spotting sea otters and anemones.',
    location: 'Emerald Cove Marine Sanctuary',
    tags: ['snorkeling', 'marine-life', 'tidepools', 'wildlife'],
  },
  {
    id: 'exp_08',
    name: 'Zero-Waste Culinary Fermentation & Sourdough Class',
    category: 'experiences',
    price: 28,
    rating: 4.9,
    sustainabilityScore: 98,
    description: 'Learn to ferment kimchi, kombucha, and maintain wild sourdough starter with take-home fermentation jar.',
    location: 'Community Food Lab',
    tags: ['cooking-class', 'fermentation', 'sourdough', 'take-home'],
  },
  {
    id: 'exp_09',
    name: 'Historic Heritage Electric Boat Cruise',
    category: 'experiences',
    price: 22,
    rating: 4.7,
    sustainabilityScore: 95,
    description: 'Silent mahogany electric launch cruising historic canals with acoustic folk music and local berry cider.',
    location: 'Waterfront Basin #2',
    tags: ['boat-cruise', 'acoustic-music', 'historic', 'relaxing'],
  },
  {
    id: 'exp_10',
    name: 'Sound Healing & Tibetan Singing Bowls in Cave',
    category: 'experiences',
    price: 24,
    rating: 4.9,
    sustainabilityScore: 99,
    description: 'Acoustic meditation session inside natural limestone cavern with resonant 432Hz crystal sound bowls.',
    location: 'Crystal Cavern Sanctuary',
    tags: ['sound-bath', 'meditation', 'cave', 'wellness', 'relaxation'],
  },
  {
    id: 'exp_11',
    name: 'Urban Pollinator Garden & Rooftop Apiary Tour',
    category: 'activities',
    price: 12,
    rating: 4.6,
    sustainabilityScore: 98,
    description: 'Observe native bees and butterfly corridors atop green roofs across downtown eco-corridor.',
    location: 'City Green Roof Hub',
    tags: ['apiary', 'bees', 'green-roof', 'pollinators'],
  },
  {
    id: 'exp_12',
    name: 'Waterfalls Greenway Self-Guided Cycling Expedition',
    category: 'activities',
    price: 10,
    rating: 4.8,
    sustainabilityScore: 100,
    description: 'Mapped 22km gravel greenway passing three secluded mountain cascades with picnic pavilions.',
    location: 'Cascades Trailhead',
    tags: ['waterfalls', 'cycling', 'gravel-trail', 'scenic-views'],
  },
  {
    id: 'exp_13',
    name: 'Upcycled Leather & Canvas Bag Crafting Studio',
    category: 'activities',
    price: 32,
    rating: 4.7,
    sustainabilityScore: 95,
    description: 'Stitch your own custom adventure tote bag using discarded sailboat sails and reclaimed leather straps.',
    location: 'Circular Makerspace',
    tags: ['upcycling', 'craft', 'fashion', 'tote-bag'],
  },
  {
    id: 'exp_14',
    name: 'Sunrise Yoga & Breathwork Over Misty Valley',
    category: 'activities',
    price: 15,
    rating: 4.9,
    sustainabilityScore: 100,
    description: 'Gentle sunrise vinyasa flow on open-air cedar platform overlooking fog-draped valley pines.',
    location: 'Lookout Cedar Deck',
    tags: ['yoga', 'sunrise', 'breathwork', 'wellness'],
  },
  {
    id: 'exp_15',
    name: 'Eco-Sculpture & Earth Art Sanctuary Walk',
    category: 'activities',
    price: 14,
    rating: 4.6,
    sustainabilityScore: 96,
    description: 'Outdoor forest art installations built purely from fallen branches, river stones, and bio-degradable fibers.',
    location: 'Sculpture Forest Park',
    tags: ['art', 'earth-art', 'sculpture', 'photogenic'],
  },
  {
    id: 'exp_16',
    name: 'Regenerative Vineyard Tour & Biodynamic Wine Flight',
    category: 'activities',
    price: 38,
    rating: 4.9,
    sustainabilityScore: 95,
    description: 'Taste low-intervention natural wines cultivated with sheep grazing and organic cover crops.',
    location: 'Terra Bella Estate',
    tags: ['natural-wine', 'vineyard', 'biodynamic', 'tasting'],
  },
  {
    id: 'exp_17',
    name: 'River Otter & Kingfisher Wildlife Watching Sanctuary',
    category: 'activities',
    price: 16,
    rating: 4.8,
    sustainabilityScore: 99,
    description: 'Quiet blind viewing of protected wetlands housing playful river otter families and migratory shorebirds.',
    location: 'North Wetland Blind',
    tags: ['wildlife', 'birdwatching', 'otters', 'peaceful'],
  },
  {
    id: 'exp_18',
    name: 'Natural Indigo Botanical Dyeing Workshop',
    category: 'activities',
    price: 28,
    rating: 4.8,
    sustainabilityScore: 97,
    description: 'Dip organic cotton bandanas and tote bags in natural fermented plant indigo vats.',
    location: 'Heritage Dye Barn',
    tags: ['indigo-dyeing', 'textiles', 'creative', 'botanical'],
  },
  {
    id: 'exp_19',
    name: 'Wildflower Seed Bomb & Native Meadow Planting',
    category: 'activities',
    price: 8,
    rating: 4.9,
    sustainabilityScore: 100,
    description: 'Make compost seed balls loaded with native lupine, poppies, and milkweed to restore degraded edges.',
    location: 'Community Nursery',
    tags: ['conservation', 'hands-on', 'rewilding', 'family-friendly'],
  },
  {
    id: 'exp_20',
    name: 'Evening Bonfire & Acoustic Lore Storytelling',
    category: 'activities',
    price: 12,
    rating: 4.8,
    sustainabilityScore: 98,
    description: 'Fireside gathering with roasted organic apples, spiced cider, and regional folklore stories.',
    location: 'Pine Grove Fire Pit',
    tags: ['bonfire', 'storytelling', 'cider', 'evening-chill'],
  },
];
